laprint/laprint/blueprints/laprint.py
### Interacting with the sqlite3 database

import sqlite3
from flask import Blueprint, request, g, redirect, url_for, \
render_template, current_app

bp = Blueprint('laprint', __name__)

### DATABASE SERVICES ###
def connect_db():
	"""get database connection"""
	rv = sqlite3.connect(current_app.config['DATABASE'])
	rv.row_factory = sqlite3.Row
	return rv

def get_db():
	"""returns the db context or creates a new one if none exists"""
	if not hasattr(g, 'sqlite_db'):
		g.sqlite_db = connect_db()
	g.sqlite_db.row_factory = sqlite3.Row
	return g.sqlite_db

def init_db():
	"""initializes the database, use this for testing purposes"""
	db = get_db()
	with current_app.open_resource('schema.sql', mode = 'r') as init_file:
		db.cursor().executescript(init_file.read())
	db.commit()

def query_db(query, args=(), one=False):
    """interface for query db, enforces escaping"""
    cur = get_db().execute(query, args)
    rv = cur.fetchall()
    cur.close()
    return (rv[0] if rv else None) if one else rv

def insert_db(table, fields=(), values=()):
    
    cur = get_db().cursor()
    query = 'INSERT INTO %s (%s) VALUES (%s)' % (
        table,
        ', '.join(fields),
        ', '.join(['?'] * len(values))
    )
    cur.execute(query, values)
    get_db().commit()
    id = cur.lastrowid
    cur.close()
    return id


### SITES OF SERVICE ###

@bp.route('/')
def main():
	guess = guess_User(request.headers)
	stats = query_db('SELECT count(id) AS c FROM fingerprints', one = True)
	return render_template('main.html', stats = stats)
	
@bp.route('/fingerprint')
def fingerprint():
	guess = guess_User(request.headers)
	if guess != None:
		print("Assuming \"%s\" as correct guessphrase.." % (guess))
		return render_template('fingerprint.html', guess = guess)
	else:
		return render_template('fingerprint.html')

@bp.route('/final')
def final():
	"""Good bye message"""
	return render_template('final.html')


@bp.route('/about')
def about():
	""" small about page with impressum and contact"""
	return render_template('about.html')


def save_guess(form):
	"""Recieves a filled out form and writes the quality relevant values to db"""
	print('Writing guess confirmation..')
	visited = form['visitedfb']
	guessfeedback = "N/A" if ('guessfb' not in form) else form['guessfb'] 
	confirm = insert_db("guesses", ('visit', 'guess'), (visited, guessfeedback))
	print("Success, already wrote "+str(confirm)+" guesses.")

def create_fingerprint(guessphrase, headers):
	useragent = request.headers.get('User-Agent', 'ERROR')
	accept = request.headers.get('Accept', 'ERROR')
	accept_language = request.headers.get('Accept-Language', 'ERROR')
	accept_encoding = request.headers.get('Accept-Encoding', 'ERROR')
	insert_db("fingerprints", 
		('useragent', 'accept', 'accept_language', 'accept_encoding', 'guessphrase'),
		(useragent, accept, accept_language, accept_encoding, guessphrase))
	print("""Added Fingerprint: 
	useragent:\t%s
	accept:\t%s
	accept_language:\t%s
	accept_encoding:\t%s""" % (useragent,accept,accept_language,accept_encoding))

# WRITE PAGES
@bp.route('/addNew', methods=['POST'])
def addNew():

	if request.method == 'POST':
		print("Received guessphrase: " + request.form['guessphrase'])
		save_guess(request.form)
		if(request.form['visitedfb'] == "no"): # we don't want doubled guessphrases
			create_fingerprint(request.form['guessphrase'],request.headers)
	return redirect(url_for('laprint.final'))


### SERVICE FUNCTION ###
def guess_User(headers):
	import random
	candidates = retrieve_guess(headers)
	if len(candidates)>1: # we saw this fingerprint more than once, but we try our luck
		return random.choice(candidates)
	elif len(candidates)==1:
		# we've seen this fingerprint once already
		return candidates[0]
	else:
		return None # we've not seen this fingerprint yet, so we assume she/he is new.

def retrieve_guess(headers):
	useragent = request.headers.get('User-Agent', 'ERROR')
	accept = request.headers.get('Accept', 'ERROR')
	accept_language = request.headers.get('Accept-Language', 'ERROR')
	accept_encoding = request.headers.get('Accept-Encoding', 'ERROR')
	result = query_db("""SELECT guessphrase FROM fingerprints WHERE useragent = ?
		AND accept = ? AND accept_language = ? AND accept_encoding = ?""",
		[useragent, accept, accept_language, accept_encoding])
	candidates = [row['guessphrase'] for row in result]
	print("Found %d potential fingerprint candidates.." % (len(candidates)))
	return candidates

laprint/laprint/templates/about.html
{% extends "layout.html" %}
{% block body%}
<p>This is a sample page used for the Seminar "Learning Analytics" given by Prof. Dr. Drachsler at Johann Wolfgang Goethe University of Frankfurt am  Main, Germany. 
</p>
<p>For inquiries: Luis.Glaser@stud.uni-frankfurt.de
</p>
{% endblock %}

laprint/laprint/templates/final.html
{% extends "layout.html" %}
{% block body%}
<p>
Thank you for helping! Feel free to come back in the next few days and check, if I can still remember you! If you use a different browser or device, I will probably not be able to since most of the values collected are browser specific.
</p>
{% endblock %}

laprint/laprint/templates/fingerprint.html
{% extends "layout.html" %}
{% block body%}
<head>
	<script language="javascript" type=text/javascript>

window.onload = function() {
			// initially hiding the guessphrase input field
	var guessform = document.getElementsByName("guessphraseform");
	for (i = 0; i < guessform.length; i++){
		document.getElementById(guessform.item(i).id).style.display = "none";
		document.getElementById(guessform.item(i).id).disabled = true;
	}

	var guess = '{{guess}}'; // inserting the jinja variable of guess
	var guessdiv = document.getElementsByName("guessform");
	if (guess) {
				guessdiv.disabled = false;
			}
			else {
				document.getElementById("guessform").style.display = "none";
				document.getElementById("guessform").disabled = true;
			}
		}

		function showHideGuessphrase(answer){
			var guessform = document.getElementsByName("guessphraseform");
			if (answer=="yes"){

		for (i = 0; i < guessform.length; i++){
			document.getElementById(guessform.item(i).id).style.display = "none";
			document.getElementById(guessform.item(i).id).disabled = true;
		}
	}
	if (answer=="no"){
		
		for (i = 0; i < guessform.length; i++){
			document.getElementById(guessform.item(i).id).style.display = "inline";
			document.getElementById(guessform.item(i).id).disabled = false;
		}
	}

}
	</script>

</head>
<div class=text> Thank you for helping me! 
	        <p> Please fill out the form below correctly. If I think I saw your fingerprint already, I will present you that <em>guessphrase</em> that you have entered when visiting earlier. This can be anything, I suggest making it something personal that you can easily recognize it again.</p>
</div>
<form id = "fingerprint_form" action="{{ url_for('laprint.addNew') }}" method = post>
	<div name = "guessform" id = "guessform">
		<p> I have found a fingerprint that correspondents to yours. It's guessphrase is: <em>{{guess}}</em>.
		</p>
		<label class="guesslabel">Was my guess right?</label>
		<div class="">
			<div style = "text-indent:2em;">
				<input type="radio" name="guessfb" value="yes"> Yes </input>
			</div>
		</div>
		<div class="">
			<div style = "text-indent:2em;">
				<input type="radio" name="guessfb"  value="no"> No </input>
			</div>
		</div>
	</div>
	<div class="visitedform">
		<label class="visitedlabel">Have you already visited?</label>
		<div class="">
			<div style = "text-indent:2em;">
				<input type="radio" name="visitedfb" onchange="showHideGuessphrase(this.value)" value="yes" checked> Yes </input>
			</div>
		</div>
		<div class = "">
			<div style = "text-indent:2em;">
				<input type="radio" name="visitedfb" onchange="showHideGuessphrase(this.value)" value="no" > No </input>
			</div>
		</div>
	</div>
	<div class="guessphraseform" id="guessphraseform" name="guessphraseform">
		<label class="guessphrase_label">
			Please provide a guessphrase:
			<input name="guessphrase" type="text"></input>
		</label>
	</div>
</div>
<div class="form_group">
	<button class="btn btn-primary" name="submit" type="submit">
		Submit
	</button>
</div>
</form>


{% endblock %}

laprint/laprint/templates/layout.html
<!doctype html>
<title>Example Fingerprinter</title>
<link rel=stylesheet type=text/css href="{{url_for('static', filename='style.css') }}">
<div class=page>
	<h1>Fingerprinting for Learning Analytics</h1>
	<div class="navbar">
		<a href="{{ url_for('laprint.main') }}"><button>Home</button></a>
		<a href="{{ url_for('laprint.about') }}"><button>About</button></a>
	</div>
  {% block body %}{% endblock %}
</div>

laprint/laprint/templates/main.html
{% extends "layout.html" %}
{% block body%}
<p>
	Welcome to Fingerprinting for Learning Analytics, a sample page for creating fingerprints for visiting users. We created <em>{{stats.c|safe}} fingerprints</em> already. 
</p>
<p>
	If you want to help, please fill out the form that is linked below. I will then create a fingerprint of your browser. To test how well this technique performs you will be asked to provide a phrase or a word that I will connect with that fingerprint. This can be anything, but it should be individual to you to remember it easily. Also, I will try to figure out, if you have already visited the site and present you that phrase. 
</p>
<p>
	If you agree to collecting your browser fingerprint, click below. I will only collect these for a seminar task and discard them afterwards.
</p>
<div class = "Fingerprintlink">
	<a href = "{{ url_for('laprint.fingerprint') }}"><button>Add/Check your fingerprint</button></a>
</div>
{% endblock %}